### ISSUE TITLE
Question about 'ex2/DoomMyWayHomeCustom-v0'

### ISSUE THREAD

**Issue by jaekyeom** [jcoreyes/ex2#1]
[exps/doom.py](https://github.com/jcoreyes/ex2/blob/master/exps/doom.py#L77) specifies `ex2/DoomMyWayHomeCustom-v0` as the environment name to use. I believe that this environment is what the paper refers to as `DoomMyWayHome+`.

However, I cannot find part the environment is registered. [register_custom_envs](https://github.com/jcoreyes/ex2/blob/master/envs/__init__.py#L7) doesn't include the Doom environment. And, as far as I know, [my_way_home2.wad](https://github.com/jcoreyes/ex2/blob/master/envs/doom/assets/my_way_home2.wad) is not enough to be used for registering a Gym environment. For instance, in [ppaquette/gym-doom](https://github.com/ppaquette/gym-doom/blob/master/ppaquette_gym_doom/doom_env.py#L40), each environment setting consists of `(config (.cfg file), scenario (.wad file), map, difficulty, actions, min, target)`.

Could you help me use that environment, please?

**Comment by jcoreyes** [comment]
I've added the full modified doom repo which contains the registration for the custom doom env in 7a082ce0000927fba9e810fa8c676046a3d95788.

**Comment by jaekyeom** [comment]
Thank you for updating the repository!
